// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('./Verifier');
var Proof = require('../../zokrates/proof.json');

contract('Verifier', accounts => {

    describe('zK-SNARKS validation proof', function () {
        beforeEach(async () => {
            this.contract = await Verifier.new();
        });
        it('validate correct proof', async () => {
            let verified = await this.contract.verifyTx(Proof.proof, Proof.inputs)
            assert.equal(verified, true);
        })
        it('validate proof is not correct', async () => {
            let verified = await this.contract.verifyTx(Proof.proof, [1, 3]);
            assert.equal(verified, false);
        })
    })
})